name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get
        working-directory: breakeven_frontend_web

      - name: Build Flutter Web
        run: flutter build web
        working-directory: breakeven_frontend_web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: breakeven_frontend_web/build/web
